### ISSUE TITLE
ion.Decimal MarshalJSON & UnmarshalJSON

### ISSUE THREAD

**Issue by plopezlpz** [amazon-ion/ion-go#176]
Is there a reason `ion.Decimal` does not implement `MarshalJSON` and `UnmarshalJSON`?

I'm happy to create a PR if it is appropriate to add those.

**Comment by arvenil** [comment]
It's a pain to use ion.Decimal. You can't use it in structs that you want to marshal/unmarshal to JSON at some point.

**Comment by popematt** [comment]
Okay, so first thing—I'm sorry it has taken so long for one of the Ion maintainers to respond to you.

The only reason `ion.Decimal` does not implement `MarshalJSON` and `UnmarshalJSON` is because no one has done it. There's no reason it can't be added, and we would welcome a PR.

Whenever someone does work on this, the conversion of `ion.Decimal` to Json should follow the convention set out [here](https://amzn.github.io/ion-docs/guides/cookbook.html#down-converting-to-json).
