### ISSUE TITLE
Why is v 1.4 not released? 

### ISSUE THREAD

**Issue by Vingtoft** [amazon-ion/ion-go#189]
New features in version 1.4 (such as custom marshal and unmarshal) are not yet released. Why not?

**Comment by popematt** [comment]
Thanks for bringing this to our attention. I'm not sure why (as it was almost a year ago 😬), but if I had to guess, it's probably because no one asked us to create a new release.

I've just created a new release ([ion-go@v1.2.0](https://github.com/amazon-ion/ion-go/releases/tag/v1.2.0)) that includes the  feature added in #185.

Please let us know if you have any issues with it.
